Add 'navigate' as valid request ModeType
facebook/flow pull request #8814
Opened 2021-12-02 21:32 UTC by comp615

Currently, in a SW, checking if the request is a full document reload might be done as request.mode === 'navigate'. However, this raises a flow error.

https://developer.mozilla.org/en-US/docs/Web/API/Request/mode

2021-12-03 02:54 UTC, mroch requested changes

2021-12-03 02:54 UTC, mroch commented on lib/bom.js
> +type ModeType = 'cors' | 'no-cors' | 'same-origin' | 'navigate;
missing closing quote :)

2021-12-05 00:37 UTC, comp615 commented on lib/bom.js
> +type ModeType = 'cors' | 'no-cors' | 'same-origin' | 'navigate;
Well that's embarrassing

2021-12-05 21:20 UTC, mroch approved these changes
thanks!

2021-12-06 18:36 UTC, closed without merging