[core] Add a few missing ES additions
facebook/flow pull request #9084
Opened 2023-09-27 14:02 UTC by pascalduez

Namely,

`Array.prototype.findLastIndex()` [ES2023]    
MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLastIndex
Spec https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.findlastindex

`String.prototype.at()` [ES2022]    
MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/at
Spec https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.at

`TypedArray.prototype.at()` [ES2022]    
MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/at
Spec https://tc39.es/ecma262/multipage/indexed-collections.html#sec-%typedarray%.prototype.at 

`Object.hasOwn()` [ES2022]    
MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn  
Spec https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-object.hasown

2023-09-27 15:05 UTC, SamChou19815 requested changes
You need to update the stuff in newtests as well. You can run `./tool record`

2023-09-27 18:10 UTC, pascalduez commented
> You need to update the stuff in newtests as well. You can run `./tool record`

Done.

2023-09-27 18:21 UTC, SamChou19815 requested changes
Otherwise looks good

2023-09-27 20:49 UTC, pascalduez commented on newtests/autostop/test.js
> +       ),
And reverted ;)    
This was indeed looking suspicious.

2023-09-28 01:27 UTC, SamChou19815 approved these changes

2023-09-28 02:17 UTC, closed without merging